const $=id=>document.getElementById(id);
const state={mode:"NORMAL",total:18,hunter:5,runner:13,boss:0,mission:0,safe:4,log:[]};
let audioCtx=null;
function getAudioCtx(){if(!audioCtx){const Ctx=window.AudioContext||window.webkitAudioContext;if(Ctx)audioCtx=new Ctx()}if(audioCtx&&audioCtx.state==="suspended")audioCtx.resume();return audioCtx}
function tone(freq=520,dur=.18,type="sine",delay=0){const ctx=getAudioCtx();if(!ctx)return;const now=ctx.currentTime+delay;const osc=ctx.createOscillator();const gain=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,now);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.11,now+.02);gain.gain.exponentialRampToValueAtTime(.0001,now+dur);osc.connect(gain);gain.connect(ctx.destination);osc.start(now);osc.stop(now+dur+.02)}
function sound(type){if(type==="SAFE"){tone(660,.16);tone(880,.18,"sine",.13)}else if(type==="LIVE"){tone(523,.14);tone(659,.14,"sine",.12);tone(784,.2,"sine",.24)}else if(type==="MISSION"){tone(720,.1,"square");tone(960,.12,"square",.16)}else if(type==="BOSS"){tone(130,.38,"sawtooth");tone(70,.42,"square",.12)}else if(type==="FINAL"){tone(440,.18,"sawtooth");tone(660,.18,"sawtooth",.22);tone(440,.18,"sawtooth",.44);tone(80,.7,"square")}else if(type==="END"){tone(523,.14);tone(784,.18,"sine",.16);tone(1046,.25,"sine",.32)}else{tone(520,.16);tone(780,.18,"sine",.16)}}
function overlay(type,icon,text){const o=$("overlay");$("overlayIcon").textContent=icon;$("overlayText").textContent=text;o.className="overlay "+type.toLowerCase();setTimeout(()=>o.classList.add("hidden"),1400)}
function command(type,msg){const id=Date.now()+"_"+Math.random().toString(16).slice(2);localStorage.setItem("street_survival_admin_command",JSON.stringify({id,type,message:msg||type,at:new Date().toISOString()}));apply(type);sound(type);overlay(type,iconFor(type),type);addLog("📡 "+type+(msg?" / "+msg:""))}
function iconFor(type){return {NORMAL:"🌆",ALERT:"⚠",BOSS:"👹",MISSION:"🎯",LIVE:"🎵",SAFE:"🛡",FINAL:"🔥",END:"🏆",RADIO:"📻"}[type]||"📡"}
function apply(type){if(type==="NORMAL"){state.mode="NORMAL";state.boss=0;state.mission=0}if(type==="ALERT"){state.mode="ALERT"}if(type==="BOSS"){state.mode="BOSS";state.boss=1}if(type==="MISSION"){state.mode="ALERT";state.mission=1}if(type==="LIVE"){state.mode="LIVE"}if(type==="SAFE"){state.mode="SAFE"}if(type==="FINAL"){state.mode="FINAL";state.boss=1;state.mission=1}if(type==="END"){state.mode="END";state.boss=0;state.mission=0}render()}
function addLog(t){const now=new Date().toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit",second:"2-digit"});state.log.unshift(`[${now}] ${t}`);state.log=state.log.slice(0,80);render()}
function render(){$("modeBadge").textContent=state.mode;$("total").textContent=state.total;$("hunter").textContent=state.hunter;$("runner").textContent=state.runner;$("boss").textContent=state.boss;$("mission").textContent=state.mission;$("safe").textContent=state.safe;$("log").innerHTML=state.log.map(x=>`<div>${x}</div>`).join("")}
document.addEventListener("DOMContentLoaded",()=>{$("normalBtn").onclick=()=>command("NORMAL","通常モード");$("alertBtn").onclick=()=>command("ALERT","警戒情報");$("bossBtn").onclick=()=>command("BOSS","新町にボス出現");$("missionBtn").onclick=()=>command("MISSION","本町集合");$("liveBtn").onclick=()=>command("LIVE","オルタネーターズLIVE開始");$("safeBtn").onclick=()=>command("SAFE","お宿 Onn SAFE発動");$("finalBtn").onclick=()=>command("FINAL","FINAL BATTLE");$("endBtn").onclick=()=>command("END","GAME END");$("radioBtn").onclick=()=>{const m=$("radioInput").value||"運営速報";localStorage.setItem("street_survival_admin_command",JSON.stringify({id:Date.now()+"",type:"RADIO",message:m,at:new Date().toISOString()}));sound("MISSION");overlay("MISSION","📻","RADIO");addLog("📻 "+m)};document.querySelectorAll("[data-sound]").forEach(b=>b.onclick=()=>{const t=b.dataset.sound.toUpperCase();sound(t);overlay(t,iconFor(t),t);addLog("🔊 "+t+" SOUND")});addLog("ADMIN ONLY 起動");render()});